import img5 from "../../Image/prop6.jpg";
import img6 from "../../Image/prop8.jpg";
import img7 from "../../Image/prop1.jpeg";
import img8 from "../../Image/prop6.jpg";
import img1 from "../../Image/prop3.jpeg";
import img2 from "../../Image/prop4.jpeg";
import img3 from "../../Image/prop5.png";
import img4 from "../../Image/prop9.jpg";


export const data = [
  {
    id: 1,
    time: "12",
    open: "11/20",
    img: img5,
    price: "999,000 ",
    bd: "1",
    ba: "1",
    sq: "801",
    address: "132 Obodo venue, Hoston Texas",
    squareFeet: "House for sale",
    details: "",
  },
  {
    id: 2,
    time: "13",
    open: "2/13",
    img: img6,
    price: "870,000",
    bd: "",
    ba: "1",
    sq: "680",
    address: "flat 4, Tina crescent, Abu dhabi, Dubia",
    squareFeet: "703/sqft",
    details: "con...",
  },
  {
    id: 3,
    time: "14",
    open: "7",
    img: img7,
    price: "949,000",
    bd: "1",
    ba: "1",
    sq: "877",
    address: "66 Taibat Ave, New Jersey",
    squareFeet: "723/sqft",
    details: "H...",
  },
  {
    id: 4,
    time: "14",
    open: "11/21",
    img: img8,
    price: "1,150,000",
    bd: "3",
    ba: "1",
    sq: "1390",
    address: "11145 Elijah St, 43 San fransisco",
    squareFeet: "House for sale",
    details: "Con...",
  },

  {
    id: 5,
    time: "12",
    open: "11/20",
    img: img1,
    price: "999,000 ",
    bd: "1",
    ba: "1",
    sq: "801",
    address: "132 Obodo venue, Lagos Nigeria",
    squareFeet: "House for sale",
    details: "",
  },
  {
    id: 6,
    time: "13",
    open: "2/13",
    img: img2,
    price: "870,000",
    bd: "",
    ba: "1",
    sq: "680",
    address: "flat 4, Tina crescent, Lagos Nigeria",
    squareFeet: "703/sqft",
    details: "con...",
  },
  {
    id: 7,
    time: "14",
    open: "7",
    img: img3,
    price: "949,000",
    bd: "1",
    ba: "1",
    sq: "877",
    address: "66 Taibat Ave, Lagos Nigeria",
    squareFeet: "723/sqft",
    details: "H...",
  },
  {
    id: 8,
    time: "14",
    open: "11/21",
    img: img4,
    price: "1,150,000",
    bd: "3",
    ba: "1",
    sq: "1390",
    address: "11145 Elijah St, 43 Lagos Nigeria",
    squareFeet: "House for sale",
    details: "Con...",
  },

];
